In [23]:
import numpy as np
import time

# Define the matrices
matrices = [
    np.array([[2, 1],
              [1, 0]]),
    np.array([[2, 1, 0],
              [1, 0, 1],
              [0, 1, 0]]),
    np.array([[2, 1],
              [-1, 1],
              [1, 1],
              [2, -1]]),
    np.array([[1, 1, 0],
              [-1, 0, 1],
              [0, 1, -1],
              [1, 1, -1]]),
    np.array([[1, 1, 0],
              [-1, 0, 1],
              [0, 1, -1],
              [1, 1, -1]]),
    np.array([[0, 1, 1],
              [0, 1, 0],
              [1, 1, 0],
              [0, 1, 0],
              [1, 0, 1]])
]

# Compute SVD for each matrix and measure time taken
for i, matrix in enumerate(matrices):
    print(f"Matrix {i}:")
    start_time = time.time()
    u, s, vh = np.linalg.svd(matrix)
    end_time = time.time()
    print("u matrix:")
    print(u,"\n")
    print("v matrix:")
    print(vh,"\n")
    print("singular values:")
    print(s)
    print("Time taken:", end_time - start_time, "seconds")
    
#Checking correctness
def dig(A,x):
    y = np.zeros_like(A)
    for i in range(len(x)):
        y[i][i] = x[i]
    return(y)
for i, matrix in enumerate(matrices):
    u, s, vh = np.linalg.svd(matrix)
    print( np.dot(u,np.dot(dig(matrices[i],s),vh)))
    if np.allclose(matrices[i], np.dot(u,np.dot(dig(matrices[i],s),vh)),0.5):
        print("\n The svd is correct.")
    else:
        print("\n The product doesn't match with the original matrix.")
    

Matrix 0:
u matrix:
[[-0.92387953 -0.38268343]
 [-0.38268343  0.92387953]] 

v matrix:
[[-0.92387953 -0.38268343]
 [ 0.38268343 -0.92387953]] 

singular values:
[2.41421356 0.41421356]
Time taken: 0.0009992122650146484 seconds
Matrix 1:
u matrix:
[[-0.88765034 -0.23319198  0.39711255]
 [-0.42713229  0.73923874 -0.52065737]
 [-0.17214786 -0.63178128 -0.75578934]] 

v matrix:
[[-0.88765034 -0.42713229 -0.17214786]
 [ 0.23319198 -0.73923874  0.63178128]
 [ 0.39711255 -0.52065737 -0.75578934]] 

singular values:
[2.4811943  1.17008649 0.68889218]
Time taken: 0.0 seconds
Matrix 2:
u matrix:
[[-0.63245553 -0.5        -0.52229321 -0.27786652]
 [ 0.31622777 -0.5        -0.30196857  0.74753928]
 [-0.31622777 -0.5         0.79704714  0.12130893]
 [-0.63245553  0.5        -0.02721464  0.59098169]] 

v matrix:
[[-1. -0.]
 [-0. -1.]] 

singular values:
[3.16227766 2.        ]
Time taken: 0.0 seconds
Matrix 3:
u matrix:
[[-4.36435780e-01 -4.08248290e-01  7.07106781e-01 -3.77964473e-01]
 [ 4.36435780